vich_uploader:
    db_driver: orm
    mappings:
        service_logo:
            uri_prefix: /uploads/service/logo
            upload_destination: '%kernel.project_dir%/web/uploads/service/logo'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
            namer: vich_uploader.namer_origname
        event_img:
            uri_prefix: /uploads/event
            upload_destination: '%kernel.project_dir%/web/uploads/event'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
            namer: vich_uploader.namer_origname