<?php

namespace AppBundle\Repository;

/**
 * AnonymousBeneficiaryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnonymousBeneficiaryRepository extends \Doctrine\ORM\EntityRepository
{

}
