<?php

namespace AppBundle\Repository;

use Doctrine\ORM\NonUniqueResultException;

/**
 * BookedShiftRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookedShiftRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $shift
     * @return mixed
     * @throws NonUniqueResultException
     */
    public function findFirstDismissed($shift)
    {
        $qb = $this->createQueryBuilder('s');

        $qb
            ->where('s.shift = :shift')
            ->andWhere('s.isDismissed = 1')
            ->setParameter('shift', $shift)
            ->orderBy('s.dismissedTime', 'ASC')
            ->setMaxResults(1);

        return $qb
            ->getQuery()
            ->getOneOrNullResult();
    }

    /**
     * @param $user
     * @return mixed
     * @throws NonUniqueResultException
     */
    public function findFirst($user)
    {
        $qb = $this->createQueryBuilder('a');

        $qb
            ->join('a.shifter', "ben")
            ->join('a.shift', "s")
            ->where('ben.user = :user')
            ->setParameter('user', $user)
            ->andWhere('a.isDismissed = 0')
            ->orderBy('s.start', 'ASC')
            ->setMaxResults(1);

        return $qb
            ->getQuery()
            ->getOneOrNullResult();
    }
}
