<?php

namespace AppBundle\Repository;

/**
 * BookedShiftRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookedShiftRepository extends \Doctrine\ORM\EntityRepository
{
}
