<?php

namespace AppBundle\Repository;

/**
 * CodeDeviceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CodeDeviceRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllIndexedById()
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT d FROM AppBundle:CodeDevice d INDEX BY d.id');

        return $query->getResult(Query::HYDRATE_ARRAY);
    }
}
