<?php

namespace AppBundle\Repository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAll()
    {
        return $this->findBy(array(), array('date' => 'DESC'));
    }

    public function findFutures(\DateTime $max = null)
    {
        $qb = $this->createQueryBuilder('e')
            ->where('e.date > :now')
            ->setParameter('now', new \Datetime('now'));

        if ($max) {
            $qb
                ->andWhere('e.date < :max')
                ->setParameter('max', $max);
        }

        $qb->orderBy('e.date', 'ASC');

        return $qb
            ->getQuery()
            ->getResult();
    }

    public function findPast(int $limit = null)
    {
        $qb = $this->createQueryBuilder('e')
            ->where('e.date < :now')
            ->setParameter('now', new \Datetime('now'));

        if ($limit) {
            $qb->setMaxResults($limit);
        }

        $qb->orderBy('e.date', 'DESC');

        return $qb
            ->getQuery()
            ->getResult();
    }
}
