<?php

namespace AppBundle\Repository;

/**
 * EventKindRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventKindRepository extends \Doctrine\ORM\EntityRepository
{
}
