<?php

namespace AppBundle\Repository;

/**
 * HelloassoPaymentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HelloassoPaymentRepository extends \Doctrine\ORM\EntityRepository
{
}
