<?php

namespace AppBundle\Repository;

/**
 * HelloassoNotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HelloassoNotificationRepository extends \Doctrine\ORM\EntityRepository
{
}
