<?php

namespace AppBundle\Repository;

/**
 * MembershipLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MembershipLogRepository extends \Doctrine\ORM\EntityRepository
{
}
