<?php

namespace AppBundle\Repository;

use AppBundle\Entity\OpeningHourKind;

/**
 * OpeningHourRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OpeningHourRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAll(OpeningHourKind $openingHourKind = null)
    {
        $qb = $this->createQueryBuilder('oh')
            ->leftJoin('oh.kind', 'ohk')
            ->addSelect('ohk');

        if ($openingHourKind) {
            $qb
                ->andwhere('oh.kind = :kind')
                ->setParameter('kind', $openingHourKind);
        }

        $qb
            ->addOrderBy('ohk.id', 'ASC')
            ->addOrderBy('oh.dayOfWeek', 'ASC')
            ->addOrderBy('oh.start', 'ASC');

        return $qb
            ->getQuery()
            ->getResult();
    }

    public function findOngoing(OpeningHourKind $openingHourKind = null)
    {
        $qb = $this->createQueryBuilder('oh')
            ->leftJoin('oh.kind', 'ohk')
            ->addSelect('ohk')
            ->andwhere('ohk.enabled = 1');

        if ($openingHourKind) {
            $qb
                ->andwhere('oh.kind = :kind')
                ->setParameter('kind', $openingHourKind);
        }

        $qb
            ->addOrderBy('ohk.id', 'ASC')
            ->addOrderBy('oh.dayOfWeek', 'ASC')
            ->addOrderBy('oh.start', 'ASC');

        return $qb
            ->getQuery()
            ->getResult();
    }

    public function findByDay(\DateTime $date, OpeningHourKind $openingHourKind = null, bool $onlyOpeningHourKindEnabled = false, bool $excludeClosed = false)
    {
        $qb = $this->createQueryBuilder('oh')
            ->leftJoin('oh.kind', 'ohk')
            ->addSelect('ohk')
            ->where('oh.dayOfWeek = :dayOfWeek')
            ->setParameter('dayOfWeek', $date->format('N') - 1);

        if ($openingHourKind) {
            $qb
                ->andwhere('oh.kind = :kind')
                ->setParameter('kind', $openingHourKind);
        }

        if ($onlyOpeningHourKindEnabled) {
            $qb
                ->andwhere('ohk.enabled = 1');
        }

        if ($excludeClosed) {
            $qb
                ->andwhere('oh.closed = 0');
        }

        $qb
            ->addOrderBy('ohk.id', 'ASC')
            ->addOrderBy('oh.dayOfWeek', 'ASC')
            ->addOrderBy('oh.start', 'ASC');

        return $qb
            ->getQuery()
            ->getResult();
    }
}
