<?php

namespace AppBundle\Repository;

/**
 * OpeningHourRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OpeningHourRepository extends \Doctrine\ORM\EntityRepository
{
}
