<?php

namespace AppBundle\Repository;

use AppBundle\Entity\PeriodPosition;

/**
 * PeriodPositionFreeLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PeriodPositionFreeLogRepository extends \Doctrine\ORM\EntityRepository
{
}
