<?php

namespace AppBundle\Repository;

/**
 * PeriodRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PeriodRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAll($dayOfWeek = null, $job = null, $withShifters = null)
    {
        $qb = $this->createQueryBuilder('p')
            ->leftJoin('p.job', 'j')
            ->addSelect('j')
            ->leftJoin('p.positions', 'pp')
            ->addSelect('pp');

        if (isset($dayOfWeek)) {
            $qb
                ->andWhere('p.dayOfWeek = :dayOfWeek')
                ->setParameter('dayOfWeek', $dayOfWeek);
        }

        if ($job) {
            $qb
                ->andWhere('p.job = :job')
                ->setParameter('job', $job);
        }

        if ($withShifters) {
            $qb
                ->leftJoin('pp.shifter', 'b')
                ->addSelect('b')
                ->leftJoin('b.user', 'u')
                ->addSelect('u')
                ->leftJoin('b.membership', 'm')
                ->addSelect('m')
                ->leftJoin("m.registrations", "r")
                ->addSelect("r")
                ->leftJoin("r.helloassoPayment", "rhp")
                ->addSelect("rhp")
                ->leftJoin("m.membershipShiftExemptions", "mse")
                ->addSelect("mse");
        }

        $qb->orderBy('p.start', 'ASC');

        return $qb
            ->getQuery()
            ->getResult();
    }
}
