<?php

namespace AppBundle\Repository;

/**
 * ProcessUpdateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProcessUpdateRepository extends \Doctrine\ORM\EntityRepository
{
}
