<?php

namespace AppBundle\Repository;

/**
 * ShiftFreeLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShiftFreeLogRepository extends \Doctrine\ORM\EntityRepository
{
}
