<?php

namespace AppBundle\Repository;

/**
 * SocialNetworkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SocialNetworkRepository extends \Doctrine\ORM\EntityRepository
{
}
