<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AddressRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddressRepository extends EntityRepository {}
