<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CodeRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CodeRepository extends EntityRepository {}
