<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommissionRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommissionRepository extends EntityRepository
{
    public function findByString($value): ?array
    {
        return $this->createQueryBuilder('c')
            ->andWhere('c.name like :val')
            ->setParameter('val', '%' . $value . '%')
            ->orderBy('c.id', 'ASC')
            ->setMaxResults(20)
            ->getQuery()
            ->getResult()
        ;
    }
}
