<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DynamicContentRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DynamicContentRepository extends EntityRepository {}
