<?php

namespace App\Repository;

/**
 * DynamicContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DynamicContentRepository extends \Doctrine\ORM\EntityRepository
{
}
