<?php

namespace App\Repository;

/**
 * EmailTemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailTemplateRepository extends \Doctrine\ORM\EntityRepository
{
}
