<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * HelloassoPaymentRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HelloassoPaymentRepository extends EntityRepository
{
    public function findOrphan()
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('p')
            ->from($this->_entityName, 'p')
            ->where('p.registration IS NULL')
        ;

        return $qb->getQuery()->getResult();
    }
}
