<?php

namespace App\Repository;

/**
 * HelloassoPaymentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HelloassoPaymentRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOrphan()
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('p')
            ->from($this->_entityName, 'p')
            ->where('p.registration IS NULL');

        return $qb->getQuery()->getResult();
    }
}
