<?php

namespace App\Repository;

/**
 * MembershipShiftExemptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MembershipShiftExemptionRepository extends \Doctrine\ORM\EntityRepository
{
}
