<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MembershipShiftExemptionRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MembershipShiftExemptionRepository extends EntityRepository {}
