<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NoteRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoteRepository extends EntityRepository {}
