<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OpeningHourKindRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OpeningHourKindRepository extends EntityRepository
{
    public function findAll()
    {
        return $this->findBy([], ['id' => 'ASC']);
    }

    public function findEnabled()
    {
        return $this->findBy(['enabled' => 1]);
    }
}
