<?php

namespace App\Repository;

/**
 * PeriodRoomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PeriodPositionRepository extends \Doctrine\ORM\EntityRepository
{
}
