<?php

namespace App\Repository;

use App\Entity\Membership;
use App\Entity\PeriodPosition;

/**
 * PeriodPositionFreeLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PeriodPositionFreeLogRepository extends \Doctrine\ORM\EntityRepository
{
    public function getMemberPeriodPositionFreed(Membership $member)
    {
        $qb = $this->createQueryBuilder('ppfl')
            ->where('ppfl.beneficiary IN (:beneficiaries)')
            ->setParameter('beneficiaries', $member->getBeneficiaries());

        $qb->orderBy('ppfl.createdAt', 'DESC');

        return $qb
            ->getQuery()
            ->getResult();
    }
}
