<?php

namespace App\Repository;

/**
 * ProxyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProxyRepository extends \Doctrine\ORM\EntityRepository
{
}
