<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProxyRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProxyRepository extends EntityRepository {}
