<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RegistrationRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegistrationRepository extends EntityRepository {}
