<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ServiceRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceRepository extends EntityRepository {}
