<?php

namespace App\Repository;

/**
 * ShiftExemptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShiftExemptionRepository extends \Doctrine\ORM\EntityRepository
{
}
