<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ShiftExemptionRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShiftExemptionRepository extends EntityRepository {}
