<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SocialNetworkRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SocialNetworkRepository extends EntityRepository
{
    public function findAllDisplayedFooter()
    {
        $qb = $this->createQueryBuilder('sn')
            ->where('sn.displayedFooter = 1')
        ;

        return $qb
            ->getQuery()
            ->getResult()
        ;
    }
}
