<?php

namespace App\Repository;

/**
 * SocialNetworkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SocialNetworkRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllDisplayedFooter()
    {
        $qb = $this->createQueryBuilder('sn')
            ->where('sn.displayedFooter = 1');

        return $qb
            ->getQuery()
            ->getResult();
    }
}
