<?php

namespace App\Repository;

/**
 * SwipeCardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SwipeCardRepository extends \Doctrine\ORM\EntityRepository
{
    public function findLastEnable($code = null,$beneficiary_id = null)
    {

        $qb = $this->createQueryBuilder('s');

        $qb
            ->where('s.enable = 1');
        if ($code){
            $qb->andWhere('s.code = :code')
                ->setParameter('code',$code);
        }
        if ($beneficiary_id){
            $qb->andWhere('s.beneficiary = :bid')
                ->setParameter('bid',$beneficiary_id);
        }

        $qb->orderBy('s.number','DESC');

        return $qb
            ->getQuery()
            ->getOneOrNullResult();
    }

    public function findLast($beneficiary_id){
        $qb = $this->createQueryBuilder('s');

        $qb
            ->where('s.beneficiary = :bid')
            ->setParameter('bid',$beneficiary_id);

        $qb->orderBy('s.number','DESC');

        $qb->setMaxResults(1);

        return $qb
            ->getQuery()
            ->getOneOrNullResult();
    }
}
