<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TaskRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends EntityRepository {}
