<?php

namespace App\Repository;

use App\Entity\Membership;
use App\Entity\Shift;

/**
 * TimeLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TimeLogRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAll(Membership $member = null, Shift $shift = null, $type = null)
    {
        $qb = $this->createQueryBuilder('tl')
            ->join('tl.membership', 'm')
            ->addSelect('m')
            ->join('tl.shift', 's')
            ->addSelect('s');

        if ($member) {
            $qb
                ->andWhere('tl.membership = :member')
                ->setParameter('member', $member);
        }

        if ($shift) {
            $qb
                ->andWhere('tl.shift = :shift')
                ->setParameter('shift', $shift);
        }

        if ($type) {
            $qb
                ->andWhere('tl.type = :type')
                ->setParameter('type', $type);
        }

        return $qb
            ->getQuery()
            ->getResult();
    }
}
