<?php

namespace App\Repository;

/**
 * TimeLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TimeLogRepository extends \Doctrine\ORM\EntityRepository
{
}
