name: Integration and Functional tests

on:
  pull_request:
    branches:
      - master
      - staging
      - dev

jobs:
  setup:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: true
      matrix:
        php-versions: ['7.4']
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Cypress dependencies
      run: sudo apt update && sudo apt-get install -y xvfb libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libnss3 libxss1 libasound2 libxtst6 xauth

#       RUN CYPRESS TESTS ----------------
    - name: Run Cypress keycloak tests
      uses: cypress-io/github-action@v6
      with:
        start: npx http-server -p 8000 -c-1
        command: npm run cy:test:oidc
      env:
        CYPRESS_BASE_URL: http://localhost:8000
        CYPRESS_KEYCLOAK_URL: http://localhost:8080


